server:
  port: 22230
  netty:
    idle-timeout: 2s


spring:
  application:
    name: kt-demo-web-${server.port}

  r2dbc:
    url: r2dbc:h2:mem:///testdb
    username: sa
    password:

  cloud:
    nacos:
      discovery:
        server-addr: nacos-standalone-derby:8848
        namespace: public
        group: DEFAULT_GROUP
