server:
  port: 22222

spring:
  application:
    name: kt-demo-web-0

  r2dbc:
    url: r2dbc:h2:mem:///testdb
    username: sa
    password:

  cloud:
    nacos:
      discovery:
        server-addr: nacos-standalone-derby:8848
        namespace: public
        group: DEFAULT_GROUP
